### ISSUE TITLE
ValueError: The number of observations cannot be determined on an empty distance matrix.

### ISSUE THREAD

**Issue by sarah872** [bjtully/BioData#18]
Hi there,
thanks for this neat tool!

Unfortunately, I am getting an error when executing `KEGG-decoder -i test -o test.out -v static`.

```
Traceback (most recent call last):
  File "/home/user/user/py3-venv/bin/KEGG-decoder", line 10, in <module>
    sys.exit(main())
  File "/home/user/user/py3-venv/lib/python3.7/site-packages/KEGGDecoder/KEGG_decoder.py", line 1375, in main
    genome = hClust_euclidean(genome)
  File "/home/user/user/py3-venv/lib/python3.7/site-packages/KEGGDecoder/KEGG_clustering.py", line 10, in hClust_euclidean
    linkage_matrix = linkage(genome_df, method='average', metric='euclidean')
  File "/home/user/user/py3-venv/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 716, in linkage
    n = int(distance.num_obs_y(y))
  File "/home/user/user/py3-venv/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2276, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```

The file `test` looks like this:
```
GB1UC4431350_v1_1640001|ID:61449066|	K21498
GB1UC4431350_v1_1650001|ID:61449067|	K07480
GB1UC4431350_v1_1680001|ID:61449069|	K03630
GB1UC4431350_v1_1770001|ID:61449078|	K03630
```

**Comment by bjtully** [comment]
Thanks, @sarah872 - does this command generate the output 'test.out' and if so, what does that look like?

I have sinking suspicion this may be the result of the gene names. But I am not sure. The error is telling me that test.out isn't being generated or is being generated incorrectly.

**Comment by sarah872** [comment]
I do get the test.out.

```
Function	glycolysis	gluconeogenesis	TCA Cycle	NAD(P)H-quinone oxidoreductase	NADH-quinone oxidoreductase	F-type ATPase	V-type ATPase	Cytochrome c oxidase	Ubiquinol-cytochrome c reductase	Cytochrome o ubiquinol oxidase	Cytochrome aa3-600 menaquinol oxidase	Cytochrome c oxidase, cbb3-type	Cytochrome bd complex	RuBisCo	CBB Cycle	rTCA Cycle	Wood-Ljungdahl	3-Hydroxypropionate Bicycle	4-Hydroxybutyrate/3-hydroxypropionate	pectinesterase	diacetylchitobiose deacetylase	glucoamylase	D-galacturonate epimerase	exo-poly-alpha-galacturonosidase	oligogalacturonide lyase	cellulase	exopolygalacturonase	chitinase	basic endochitinase B	bifunctional chitinase/lysozyme	beta-N-acetylhexosaminidase	D-galacturonate isomerase	alpha-amylase	beta-glucosidase	pullulanase	ammonia oxidation (amo/pmmo)	hydroxylamine oxidation	nitrite oxidation	dissim nitrate reduction	DNRA	nitrite reduction	nitric oxide reduction	nitrous-oxide reduction	nitrogen fixation	hydrazine dehydrogenase	hydrazine synthase	dissimilatory sulfate < > APS	dissimilatory sulfite < > APS	dissimilatory sulfite < > sulfide	thiosulfate oxidation	alt thiosulfate oxidation tsdA	alt thiosulfate oxidation doxAD	sulfur reductase sreABC	thiosulfate/polysulfide reductase	sulfhydrogenase	sulfur disproportionation	sulfur dioxygenase	sulfite dehydrogenase	sulfite dehydrogenase (quinone)	sulfide oxidation	sulfur assimilation	DMSP demethylation	DMS dehydrogenase	DMSO reductase	NiFe hydrogenase	ferredoxin hydrogenase	membrane-bound hydrogenase	hydrogen:quinone oxidoreductase	NAD-reducing hydrogenase	NADP-reducing hydrogenase	NiFe hydrogenase Hyd-1	thiamin biosynthesis	riboflavin biosynthesis	cobalamin biosynthesis	transporter: vitamin B12	transporter: thiamin	transporter: urea	transporter: phosphonate	transporter: phosphate	Flagellum	Chemotaxis	Methanogenesis via methanol	Methanogenesis via acetate	Methanogenesis via dimethylsulfide, methanethiol, methylpropanoate	Methanogenesis via methylamine	Methanogenesis via trimethylamine	Methanogenesis via dimethylamine	Methanogenesis via CO2	Coenzyme B/Coenzyme M regeneration	Coenzyme M reduction to methane	Soluble methane monooxygenase	methanol dehydrogenase	alcohol oxidase	dimethylamine/trimethylamine dehydrogenase	Photosystem II	Photosystem I	Cytochrome b6/f complex	anoxygenic type-II reaction center	anoxygenic type-I reaction center	Retinal biosynthesis	Entner-Doudoroff Pathway	Mixed acid: Lactate	Mixed acid: Formate	Mixed acid: Formate to CO2 & H2	Mixed acid: Acetate	Mixed acid: Ethanol, Acetate to Acetylaldehyde	Mixed acid: Ethanol, Acetyl-CoA to Acetylaldehyde (reversible)	Mixed acid: Ethanol, Acetylaldehyde to Ethanol	Mixed acid: PEP to Succinate via OAA, malate & fumarate	Naphthalene degradation to salicylate	Biofilm PGA Synthesis protein	Colanic acid and Biofilm transcriptional regulator	Biofilm regulator BssS	Colanic acid and Biofilm protein A	Curli fimbriae biosynthesisAdhesion	Competence-related core components	Competence-related related components	Competence factors	Glyoxylate shunt	Anaplerotic genes	Sulfolipid biosynthesis	C-P lyase cleavage PhnJ	CP-lyase complex	CP-lyase operon	Type I Secretion	Type III Secretion	Type II Secretion	Type IV Secretion	Type VI Secretion	Sec-SRP	Twin Arginine Targeting	Type Vabc Secretion	Serine pathway/formaldehyde assimilation	Arsenic reduction
GB1UC4431350	 0.78	 0.0	 1.0	 0	 0.98	 0.875	 0	 0.75	 0.5	 0	 0	 0	 0	 1	 1.0	 0	 0.0	 0.53	 0.3	 0	 0	 0	 1	 0	 0	 0	 0	 0	 0	 0	 1	 0	 1	 0	 0	 0	 0	 1	 1	 0	 1	 1	 1	 0.99	 0	 0	 1	 1	 1	 0. 1	 0	 0	 0	 0	 0	 0	 1	 0	 1	 0	 0	 0	 0	 0	 0	 0	 0	 0	 0	 0	 0.64	 1.0	 0.88	 0	 0	 1.0	 0	 1.0	 0.0	 0.0	 0	 0	 0	 0	 0	 0	 0	 0.2	 0	 0	 0	 0	 0	 0	 0	 0	 0	 0	 0	 0.5	 0	 0	 0.167	 0.5	 1	 0	 0	 0.583	 0.0	 0	 0	 0	 0	 0	 0	 0.14	 0	 0	 1	 0.25	 0	 0	 0	 0	 0.33	 0	 0.8458999999999998	 0	 0.777	 0.9129999999999999	 0.75	 0	 0.5	 0.75
```

**Comment by bjtully** [comment]
AH! Thanks for discovering this - the most recent version of the code wants to perform a clustering step on the metabolisms of multiple input genomes.
A fast (but not elegant) solution would be to include a second genome in your analysis. The slower version is that I will fix the code "soon".
test.out will allow to look at the data in Excel, just without the final picture.

**Comment by bjtully** [comment]
This issue has been "fixed" - submitting 1 genome will not trigger clustering.

**Comment by ahoiching** [comment]
Today I tried submitting only 1 genome got the same error.

**Comment by bjtully** [comment]
So the interactive output is different from the static output. The clustering is built in so that we can have the interactive display drop down menu. Currently, there are no plans to modify the code to allow interactive mode on a single genome. If you'd like use interactive, you can use two copies of the same genome as indicated above.
