### ISSUE TITLE
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

### ISSUE THREAD

**Issue by Jigyasa3** [bjtully/BioData#37]
hey!

I am running the following code using python/3.5.2-
$KEGG-decoder --input 272-14-prokka.faa-kopfam --output 272-14.list --vizoption static

On my input file which looks like this-
LAKMIEEK_00001  K06997
LAKMIEEK_00002  K09772
LAKMIEEK_00003  K01696
LAKMIEEK_00003  K01817
LAKMIEEK_00004  K01695
LAKMIEEK_00005  K03526

But I keep getting an error-
Traceback (most recent call last):
  File "/home/j/jigyasa-arora/.local/bin/KEGG-decoder", line 11, in <module>
    sys.exit(main())
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/KEGGDecoder/KEGG_decoder.py", line 1288, in main
    import pandas as pd
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from .array_ import array  # noqa: F401
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/core/arrays/array_.py", line 7, in <module>
    from pandas.core.dtypes.common import (
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/core/dtypes/common.py", line 11, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/core/dtypes/dtypes.py", line 53, in <module>
    class Registry:
  File "/home/j/jigyasa-arora/.local/lib/python3.5/site-packages/pandas/core/dtypes/dtypes.py", line 84, in Registry
    self, dtype: Union[Type[ExtensionDtype], str]
  File "/apps/free72/python/3.5.2/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/apps/free72/python/3.5.2/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/apps/free72/python/3.5.2/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/apps/free72/python/3.5.2/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/apps/free72/python/3.5.2/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

**Comment by bjtully** [comment]
The format for the input is very literal, so your current formatting would not work. 

Instead of:
```
LAKMIEEK_00001 K06997
LAKMIEEK_00002 K09772
```

It would need to be:
```
LAKMIEEK_1 K06997
LAKMIEEK_2 K09772
```
