### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by razz1618** [bjtully/BioData#51]
Hi, 
When i run , kegg decoder with my MAG ko list i get the following error. I t strange because i have successfully  used the same program a few days ago on much bigger data.

**Terminal output**
KEGG-decoder -i SN_MAG_00001-gene_calls.txt -o SN_MAG_00001-ko_FUNCTION_OUT.list -v static
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/vibrant/bin/KEGG-decoder", line 8, in <module>
    sys.exit(main())
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/KEGGDecoder/KEGG_decoder.py", line 1649, in main
    genome = hClust_euclidean(genome)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/KEGGDecoder/KEGG_clustering.py", line 15, in hClust_euclidean
    clust = dendrogram(linkage_matrix, no_plot=True, labels=names, get_leaves=True)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3347, in dendrogram
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3633, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3633, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3633, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  [Previous line repeated 57 more times]
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3600, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3633, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3633, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3633, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  [Previous line repeated 929 more times]
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3600, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3512, in _dendrogram_calculate_info
    leaf_label_func, i, labels)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3369, in _append_singleton_leaf_node
    lvs.append(int(i))
**RecursionError: maximum recursion depth exceeded while calling a Python object**

KO file
[SN_MAG_00001-gene_calls.txt](https://github.com/bjtully/BioData/files/5727297/SN_MAG_00001-gene_calls.txt)

**Comment by razz1618** [comment]
Solved. Kegg decoder expects the gene call name to start with an alphabet rather than a number. I replaced the gene name from
 1564 >> g_1564
............
and it worked.
