### ISSUE TITLE
KEGGDecoder: Amino acid pathways not visible on heatmap, -v interactive error

### ISSUE THREAD

**Issue by maherrl** [bjtully/BioData#54]
Hello,

I have two issues popping up while trying to run KEGGDecoder. Firstly, the -v static option runs without issue, but the heatmap generated does not include the amino acid pathways at the end.

Secondly, when trying to run -v interactive with modified and concatenated kofamKOALA outputs from several genomes, I get the error:

```
(KEGGdecoder) Rebeccas-MacBook-Pro:kofamKOALA Becca$ KEGG-decoder -i all.txt -o out/all.ko -v interactive
Traceback (most recent call last):
  File "/Users/Becca/miniconda3/envs/KEGGdecoder/bin/KEGG-decoder", line 8, in <module>
    sys.exit(main())
  File "/Users/Becca/miniconda3/envs/KEGGdecoder/lib/python3.8/site-packages/KEGGDecoder/KEGG_decoder.py", line 1447, in main
    plotly_viz(genome, os.path.splitext(filehandle)[0] + ".html")
  File "/Users/Becca/miniconda3/envs/KEGGdecoder/lib/python3.8/site-packages/KEGGDecoder/Plotly_viz.py", line 19, in plotly_viz
    Most_Least_genome_df = hClust_most_least(genome_df)
  File "/Users/Becca/miniconda3/envs/KEGGdecoder/lib/python3.8/site-packages/KEGGDecoder/KEGG_clustering.py", line 36, in hClust_most_least
    genome_df = genome_df.ix[sort_dex]
  File "/Users/Becca/miniconda3/envs/KEGGdecoder/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```
Any idea why I am getting this error and why I cannot visualize the amino acid pathways?

Thanks!

**Comment by bjtully** [comment]
For the missing amino acid information - have you update to the most recent version of KEGG-Decoder? You can do this with the command `pip install --upgrade KEGGDecoder`. Let me know if that works. Otherwise, we'll have to troubleshoot further.

When you concatenate kofamKOALA outputs, how genomes are are you combining? And are you able to maintain the same formatting requirements? This error tends to happen when the input file is formatted incorrectly.

**Comment by maherrl** [comment]
Thanks for the speedy response. After upgrading, the amino acid information still does not show. The upgrade completed but with the following error:

```
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/Becca/miniconda3/envs/KEGGdecoder/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zj/4b_990l14h1gy2vl132n7jl00000gn/T/pip-install-l0e7fp9x/matplotlib_471b04ccd71947f1997554652b862c3e/setup.py'"'"'; __file__='"'"'/private/var/folders/zj/4b_990l14h1gy2vl132n7jl00000gn/T/pip-install-l0e7fp9x/matplotlib_471b04ccd71947f1997554652b862c3e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zj/4b_990l14h1gy2vl132n7jl00000gn/T/pip-pip-egg-info-v61gj75e
         cwd: /private/var/folders/zj/4b_990l14h1gy2vl132n7jl00000gn/T/pip-install-l0e7fp9x/matplotlib_471b04ccd71947f1997554652b862c3e/
    Complete output (46 lines):
    IMPORTANT WARNING:
        pkg-config is not installed.
        matplotlib may not be able to find some of its dependencies
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.8.8 | packaged by conda-forge | (default, Feb
                            20 2021, 16:12:38)  [Clang 11.0.1 ]]
                  platform: yes [darwin]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.20.2]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: yes [version 1.6.37]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: yes [installing, darwin]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype
                            * Try installing freetype with `brew install
                            * freetype` and pkg-config with `brew install pkg-
                            * config`
    ----------------------------------------
```

For the second question, I combined 20 genomes and modified with your the code from the BVCN tutorial:
```
for f in *.txt; do sed 's/ \+ /\t/g' $f | cut -f1,2 | sed 's/\* //g' |  grep -v "#" > $f-mod; done
cat *mod > all.txt
```
The all.txt file appears to be in the right format:
```
(KEGGdecoder) Rebeccas-MacBook-Pro:kofamKOALA Becca$ head all.txt
NALNPDOO_00001      K22552  319.43  431.7  7.7e-130 multicopper oxidase [EC:1.16.3.1]
NALNPDOO_00004      K03599  168.70  340.4  1.6e-102 stringent starvation protein A
NALNPDOO_00004      K00799   66.23   95.0   1.2e-27 glutathione S-transferase [EC:2.5.1.18]
NALNPDOO_00005      K03600   47.43  188.3   1.5e-56 stringent starvation protein B
```

**Comment by maherrl** [comment]
Both issues resolved after installing KEGGDecoder in this anvio environment:
`(KEGGdecoder) Rebeccas-MacBook-Pro:kofamKOALA Becca$ conda create --name KEGGdecoder python=3.7 matplotlib=3.0.3`

Thanks!
