### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by wichne** [bjtully/BioData#56]
Any idea why I'm getting the following error with the attached input file?

$ KEGG-decoder -i test.txt
[test.txt](https://github.com/bjtully/BioData/files/7062986/test.txt)
 -o test.out -v static
Traceback (most recent call last):
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/bin/KEGG-decoder", line 8, in <module>
    sys.exit(main())
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/KEGGDecoder/KEGG_decoder.py", line 1443, in main
    genome = hClust_euclidean(genome)
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/KEGGDecoder/KEGG_clustering.py", line 15, in hClust_euclidean
    clust = dendrogram(linkage_matrix, no_plot=True, labels=names, get_leaves=True)
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3347, in dendrogram
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  [Previous line repeated 10 more times]
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3620, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  [Previous line repeated 22 more times]
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3620, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3653, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  [Previous line repeated 950 more times]
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3620, in _dendrogram_calculate_info
    _dendrogram_calculate_info(
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3550, in _dendrogram_calculate_info
    _append_singleton_leaf_node(Z, p, n, level, lvs, ivl,
  File "/home/nels329/anaconda3/envs/KEGG-Decoder/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 3409, in _append_singleton_leaf_node
    lvs.append(int(i))
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by bjtully** [comment]
Thanks @wichne. Not sure why I didn't do this sooner, but I have updated the installation recommendation to highlight that KEGG-Decoder can only run in Python=3.6

**Comment by JSSaini** [comment]
same issue with python 3.6

**Comment by wichne** [comment]
Hi Ben,
I found issue  #51, and figured out that it was illegal identifiers that were/are causing the problem. You do cryptically state how they should be formatted in your readme ("Be sure your submitted FASTA file has headers that group genomes together, KEGG-decoder.py groups based on the name provided in FASTA header before the first underscore (_)"), but maybe you could make that clearer to avoid this problem. And a data check by the program would also be nice.
